### ISSUE TITLE
Unable to forward email 

### ISSUE THREAD

**Issue by TuanQA92** [OpenPaaS-Suite/esn-frontend-inbox#71] opened 2020-08-20 08:22 UTC
Reproduce steps:

1. Go to https://dev.open-paas.org/ and login user A
2. Go to the SPA URL: https://dev.open-paas.org/inbox/ 
3. User A sends an email for user B
4. Login user B 
5. Open user B's email that is sent from user A
6. Click on Forward button
7. Verify issue 

Actual Results: Unable to forward the email.  It displays the error in console tab 
![image](https://user-images.githubusercontent.com/69950706/90738911-b5516a80-e2f8-11ea-8eb6-89c1eef90d1f.png)

Expected Results:  Able to forward email

**Comment by huy-ta** [comment] 2020-08-21 08:41
I cannot reproduce this bug anymore, can you verify @TuanQA92?

**Comment by huy-ta** [comment] 2020-08-27 04:11
@tlle14 Can you verify and close the issue?

**Comment by tlle14** [comment] 2020-08-27 04:25
Thank @huy-ta 

Retest pass

![fwd](https://user-images.githubusercontent.com/69950655/91384125-0bbe2c00-e858-11ea-9964-15dfcf173c96.gif)

**Closed by tlle14** 2020-08-27 04:25 UTC
Labels: Major, bug, irreproducible
