### ISSUE TITLE
99+ badges are hiding inbox icons

### ISSUE THREAD

**Issue by chamerling** [OpenPaaS-Suite/esn-frontend-inbox#315] opened 2021-01-06 11:29 UTC
Screenshot is better than a long speech

![Capture d’écran 2021-01-06 à 12 26 14](https://user-images.githubusercontent.com/264403/103763838-b3bfdf00-501a-11eb-80f7-dca1ca2f2751.png)

Suggestion: smaller badge, push them to the bottom right, make icon bigger, etc...

**Comment by fabienmoyon** [comment] 2021-02-02 11:25
WDYT @chamerling 1 or 2 ?

![Capture d’écran de 2021-02-02 12-19-44](https://user-images.githubusercontent.com/11298249/106593523-3459f880-6551-11eb-94d3-2fe3336543ea.png)

![Capture d’écran de 2021-02-02 12-24-18](https://user-images.githubusercontent.com/11298249/106593896-a92d3280-6551-11eb-822e-9d8b721b498f.png)

**Comment by chamerling** [comment] 2021-02-02 11:35
The ligher, the better

**Comment by tlle14** [comment] 2021-02-25 10:17
Hi @fabienmoyon 

# Actual Result
1. I guest 99+ is better than the exact number
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/5b1e7040-71bb-49c9-8c29-4b9961357a5a)

2. On the phone, the mailbox name is overlaying the mail counter:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/9d963d37-ae50-4260-9872-b55561465dc5)

On the web, the mail counter in the different mailboxes are not aligned:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/75e398c1-09d2-4337-8af7-5b5d224361cb)

# Expected Result
1. Please consider the suggestion
2. The mail counter and the mailbox name shouldn't be mixed up
3. It should be aligned, for example on gmail:
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/e8e0a022-8444-4b32-83eb-9fb464f6eeb5)

**Comment by fabienmoyon** [comment] 2021-03-05 18:11
Prs than fix your feedbacks @tlle14  https://github.com/OpenPaaS-Suite/esn-frontend-common-libs/pull/173 & https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/376

**Comment by fabienmoyon** [comment] 2021-03-08 09:43
Hello @tlle14, 

1. Personally I prefer to see the real number. WDYT @chamerling ?

1. Done 

1. Done

**Comment by chamerling** [comment] 2021-03-08 12:54
At least when under a given number. 99 was to small. 999 should be nice

**Comment by tlle14** [comment] 2021-03-09 04:45
Hi @fabienmoyon 
1. It's okay to display 999 instead of 99
2. The email counter is not displaying when the mailbox name is long.
=> We should have a fixed area to display the counter. 
When the mailbox name is long, it should display 3 dots for the missing part name. 
![image.png](https://images.zenhubusercontent.com/5f76a1e8a1698e3d1ae2d969/2e937769-f975-45a8-a098-09da32b4f9ef)

3. Mailbox counters of the mailboxes list are aligned. Thanks!

**Comment by fabienmoyon** [comment] 2021-03-11 19:26
Hello @tlle14,

1. Done
2. Done

https://user-images.githubusercontent.com/11298249/110842047-e8644700-82a6-11eb-82ec-f54f8f5c5401.mp4

**Comment by tlle14** [comment] 2021-03-12 02:31
@fabienmoyon , as I see in the video, it only displays correctly when hovered. 
Could you please make it always display as it has hovered?

**Comment by fabienmoyon** [comment] 2021-03-12 10:31
> @fabienmoyon , as I see in the video, it only displays correctly when hovered.
> Could you please make it always display as it has hovered?

It's the same result only the color change on hover ;)

**Comment by tlle14** [comment] 2021-03-12 10:48
This fix has a small problem. When the mailbox has no hovered, the unread counter is overlaying the mailbox name. 
=> Expect: the long mailbox name should be cut when the email counter display. 
![Peek 2021-03-12 17-35](https://user-images.githubusercontent.com/69950655/110928903-f7f09800-8359-11eb-9671-afb6839a927b.gif)

**Comment by fabienmoyon** [comment] 2021-04-13 19:00
Hello @tlle14 ?

I opened a [PR](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/pull/414) can you please have a look and tell me if for you it's fixed [the last problem](https://github.com/OpenPaaS-Suite/esn-frontend-inbox/issues/315#issuecomment-797406726) :+1: 

Regards,
Fabien

**Comment by tlle14** [comment] 2021-04-14 02:27
Hello @fabienmoyon 
Since the design has been changed, the issue is no more existing. 
I should close this issue

**Closed by tlle14** 2021-04-14 02:27 UTC
Labels: 1, QA:Testing, User Feedback
