### ISSUE TITLE
Default tab is not selected when user goes to Configuration 

### ISSUE THREAD

**Issue by hantt12** [OpenPaaS-Suite/esn-frontend-inbox#198] opened 2020-10-06 10:14 UTC
In Webmail screen, click on Configuration from the left menu

Expected result:
Configuration screen should be shown with Vacation tab selected and Vacation form is shown

Expected result:
Blank screen. No tab is selected

![Peek 2020-10-06 17-09](https://user-images.githubusercontent.com/53081477/95188886-4c19ae00-07f7-11eb-9719-501540ceeb38.gif)

**Comment by MichaelBailly** [comment] 2020-10-06 10:59
Closing, duplicate of #79

**Closed by MichaelBailly** 2020-10-06 10:59 UTC
Labels: bug, duplicate, minor
